import random

#Natural Launguage Generation
#partially generated by ChatGPT, partially written by me

#written by me
def read_file(filename):
    line_str = []
    with open(filename,'r',encoding='utf-8') as f:
        lines = f.readlines()
        for i in range(len(lines)):
            lines[i] = lines[i].strip()


    line_str = " ".join(lines)
    return line_str

def build_and_generate_markov(words, order = 2, length = 10, seed = None):
    # Step 1: Build the Markov Chain
    chain = {}
    for i in range(len(words) - order):
        key = tuple(words[i:i + order])
        next_word = words[i + order]
        if key in chain:
            chain[key].append(next_word)
        else:
            chain[key] = [next_word]

    #print(chain)
    # Step 2: Generate Text
    key = random.choice(list(chain.keys()))
    result = list(key)

    #written by me, rest of function beside print are generated
    #Starting seed
    if seed != None:
        #print("yep")
        options = []
        for k in chain:
            if k[0] == seed:
                options.append(k)
        if options:
            key = random.choice(options)
            result = list(key)




    #print()
    for _ in range(length - order):
        next_words = chain.get(key)
        if not next_words:
            break
        next_word = random.choice(next_words)
        result.append(next_word)
        key = tuple(result[-order:]) # shift the window
    #print(key)
    return ' '.join(result)


string = read_file("sample.txt")
# Example usage:
training_text = string.split()
print(build_and_generate_markov(training_text, order=3, length=1000))
print()